---
# - name: Get my user
#   ansible.builtin.set_fact:
#     remote_regular_user: '{{ ansible_facts["user_id"] }}'

# - debug:
#     msg: "Running as user: {{ remote_regular_user }}"

- name: Install base packages
  pacman:
    name:
      - git
      - kitty
      - nautilus
    state: present
    update_cache: yes
  become: true

- name: Configure pacman
  import_tasks: pacman.yml
  tags: pacman

- name: Setup AUR helper
  import_tasks: aur.yml
  tags: aur

- name: Setup CachyOS repository
  import_tasks: cachyos.yml
  tags: cachyos
