#!/usr/bin/env python3

def is_vanilla() -> bool:
    """Return whether running "vanilla" Python"""
    import sys
    return not hasattr(__builtins__, "__IPYTHON__") and "bpython" not in sys.argv[0]


def setup_history():
    import os
    import atexit
    import readline
    from pathlib import Path

    if state_home := os.environ.get("XDG_STATE_HOME"):
        state_home = Path(state_home)
    else:
        state_home = Path.home() / ".local" / "state"

    history: Path = state_home / "python" / "history"
    history.parent.mkdir(parents=True, exist_ok=True)

    # Override the default ~/.python_history readline picked up
    readline.clear_history()
    if history.exists():
        readline.read_history_file(str(history))

    # Remove Python's built-in history writer, replace with ours
    import site
    site.write_history = lambda *args, **kwargs: None  # no-op
    atexit.register(readline.write_history_file, str(history))


if is_vanilla():
    setup_history()
