#  __  __       _ _   _   __  __             _ _               _   _                        ____       _
# |  \/  |_   _| | |_(_) |  \/  | ___  _ __ (_) |_ ___  _ __  | | | | ___  _ __ ___   ___  / ___|  ___| |_ _   _ _ __
# | |\/| | | | | | __| | | |\/| |/ _ \| '_ \| | __/ _ \| '__| | |_| |/ _ \| '_ ` _ \ / _ \ \___ \ / _ \ __| | | | '_ \
# | |  | | |_| | | |_| | | |  | | (_) | | | | | || (_) | |    |  _  | (_) | | | | | |  __/  ___) |  __/ |_| |_| | |_) |
# |_|  |_|\__,_|_|\__|_| |_|  |_|\___/|_| |_|_|\__\___/|_|    |_| |_|\___/|_| |_| |_|\___| |____/ \___|\__|\__,_| .__/
#                                                                                                               |_|
# -----------------------------------------------------------------------------------------------------------------------------------------

monitor=eDP-1,preferred,0x0,1
# On the left : -1920x0, right : 1920x0, above 0x-1080, below : 0x1080
# SECONDARY MONITOR CONFIG

# Workspaces
$mainMod = SUPER
plugin {
    hyprsplit {
        num_workspaces = 3
    }
}

# hyprlang noerror true
bind = $mainMod, ampersand, split:workspace, 1
bind = $mainMod, eacute, split:workspace, 2
bind = $mainMod, quotedbl, split:workspace, 3
# bind = $mainMod, apostrophe, split:workspace, 4

bind = $mainMod SHIFT, ampersand, split:movetoworkspace, 1
bind = $mainMod SHIFT, eacute, split:movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl, split:movetoworkspace, 3
# bind = $mainMod SHIFT, apostrophe, split:movetoworkspace, 4
# hyprlang noerror false

# Other
bindl = , switch:on:Lid Switch, exec, hyprlock
