#  _               _
# | |__   __ _ ___| |__  _ __ ___
# | '_ \ / _` / __| '_ \| '__/ __|
# | |_) | (_| \__ \ | | | | | (__
# |_.__/ \__,_|___/_| |_|_|  \___|
#
# -----------------------------------------------------------------------------------------------------------------------------------------

source "$HOME/.config/shell/env"
source "$BASHDIR/config"
source "$SHELLDIR/aliases"
source "$SHELLDIR/startup"
source "$SHELLDIR/functions"

if [[ $(tty) == *"pts"* ]]; then
  # Themes are installed at /usr/share/oh-my-posh/themes.
  eval "$(oh-my-posh init bash --config spaceship)"
else
  eval "$(oh-my-posh init bash --config $HOME/.config/ohmyposh/zen.toml)"
fi
