#              _            _             _
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
#
# -----------------------------------------------------------------------------------------------------------------------------------------

$HYPRSCRIPTS = $HOME/.config/hypr/scripts

# Clean Home Directory
exec-once = $HYPRSCRIPTS/system/home-cleaner.sh

# Clean games
exec-once = $HYPRSCRIPTS/game-mode/cleanup-games.sh

# Setup XDG for screen sharing
exec-once = $HYPRSCRIPTS/system/xdg.sh

# Setup monitor configuration
# This will also restore the wallpaper and start waybar
exec-once = $HYPRSCRIPTS/monitors/monitor-check.sh
exec-once = $HYPRSCRIPTS/monitors/monitor-handler.sh
# exec-once = $HYPRSCRIPTS/waybar/launch.sh

# Start Polkit
# Gnome polkit is not supported anymore. If it stops working, switch to hyprpolkitagent.
# For now, gnome polkit is just much better.
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = systemctl --user start hyprpolkitagent

# Load Dunst Notification Manager
exec-once = dunst

# Start EWW daemon
exec-once = eww daemon

# Using hypridle to start hyprlock
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Start Hyprsunset
exec-once = $HYPRSCRIPTS/hyprsunset/hyprsunset.sh restore

# Restore Game Mode
exec-once = $HYPRSCRIPTS/game-mode/restore.sh

# Start Nextcloud
exec-once = /usr/bin/nextcloud --background

# Check VPN status
exec-once = $HYPRSCRIPTS/vpn/update-status.sh

# SDL version
env = SDL_VIDEODRIVER,wayland
