#           _           _
# __      _(_)_ __   __| | _____      _____
# \ \ /\ / / | '_ \ / _` |/ _ \ \ /\ / / __|
#  \ V  V /| | | | | (_| | (_) \ V  V /\__ \
#   \_/\_/ |_|_| |_|\__,_|\___/ \_/\_/ |___/
#
# -----------------------------------------------------------------------------------------------------------------------------------------

general {
    gaps_in = 5
    gaps_out = 5
    gaps_workspaces = 0
    border_size = 2
    no_border_on_floating = true
    # hyprlang noerror true
    col.active_border = $accent-color $highlight-color
    col.inactive_border = $accent-color-transparent
    # hyprlang noerror false
    layout = dwindle
    resize_on_border = true
    hover_icon_on_border = true

    snap {
        enabled = true
        window_gap = 20
        monitor_gap = 20
    }
}

group {
    # hyprlang noerror true
    col.border_active = $accent-color $highlight-color
    col.border_inactive = $accent-color-transparent
    # hyprlang noerror false

    groupbar {
        # font_family = Cantarell
        font_size = 16
        font_weight_active = bold
        font_weight_inactive = bold
        height = 20
        indicator_gap = 6
        indicator_height = 4
        rounding = 4
        round_only_edges = false
        # hyprlang noerror true
        col.active = $accent-color $highlight-color
        col.inactive = $accent-color-transparent
        # hyprlang noerror false
        gaps_in = 20
        gaps_out = 5
        text_color = 0xffffffff
    }
}
