#           _           _                            _
# __      _(_)_ __   __| | _____      __  _ __ _   _| | ___  ___
# \ \ /\ / / | '_ \ / _` |/ _ \ \ /\ / / | '__| | | | |/ _ \/ __|
#  \ V  V /| | | | | (_| | (_) \ V  V /  | |  | |_| | |  __/\__ \
#   \_/\_/ |_|_| |_|\__,_|\___/ \_/\_/   |_|   \__,_|_|\___||___/
#
# -----------------------------------------------------------------------------------------------------------------------------------------

windowrule {
  name = no-border-on-floating
  match:float = true

  border_size = 0
}

# Brave
windowrule {
    name = brave
    match:class = ^([Bb]rave-browser)$

    opaque = true
}

# Browser Picture in Picture
windowrule {
  name = picture-in-picture
  match:title = ^([Pp]icture[\s\-]in[\s\-][Pp]icture)$

  float = true
  pin = true
  size = 900 500
  move = 600 400
}

# Pavu control
windowrule {
    name = pavucontrol
    match:class = (.*org.pulseaudio.pavucontrol.*)

    float = true
    size = 800 600
    center = true
    pin = true
}

# Waypaper floating
windowrule {
  name = waypaper
  match:class = (.*waypaper.*)

  float = true
  size = 900 700
  center = true
  pin = true
}

# Systemupdate floating
windowrule {
  name = systemupdate
  match:title = (systemupdate)

  float = true
  size = 900 600
  center = true
}

# Sushi
windowrule {
  name = sushi
  match:class = (org.gnome.NautilusPreviewer)

  float = true
  size = 1300 900
  center = true
}

# Gnome Calculator
windowrule {
  name = gnome-calculator
  match:class = (org.gnome.Calculator)

  float = true
  size = 700 600
  center = true
}

# Gnome Calendar
windowrule {
  name = gnome-calendar
  match:class = (org.gnome.Calendar)

  float = true
  size = (monitor_w*0.3) (monitor_h*0.4)
  move = ((monitor_w/2)-window_w/2) (monitor_h*0.15)
}

# Emoji Picker Smile
windowrule {
  name = smile
  match:class = (it.mijorus.smile)

  float = true
  pin = true
  size = 500 600
  move = 1300 100
}

# Nextcloud
windowrule {
  name = nextcloud
  match:class = ^(com.nextcloud.desktopclient.nextcloud)$

  float = true
  size = 700 800
}
windowrule = move 1200 70, match:title ^(Nextcloud Settings)$
windowrule = move 1170 100, match:title ^(Nextcloud)$

# Adw-bluetooth
windowrule {
  name = adw-bluetooth
  match:class = ^(.*AdwBluetooth)$

  float = true
  size = 500 650
  center = true
}

# Folder and file picker windows using xdg desktop portal
windowrule {
  name = file-folder-picker
  match:class = ^(xdg-desktop-portal-gtk)$

  float = true
  size = 1000 700
  center = true
}

# Folder and file picker windows
windowrule {
  name = file-folder-picker
  match:title = ^(Select Folder)$|^(Select File)$|^(Open Folder)$|^(Open File)$

  float = true
  size = 1000 700
  center = true
}

windowrule {  # For Sublime
  name = file-folder-picker-bis
  match:initial_title = ^(Select Folder)$|^(Select File)$|^(Open Folder)$|^(Open File)$

  float = true
  size = 1000 700
  center = true
}

# Bitwarden
windowrule {
  name = bitwarden
  #match:title = ^(Bitwarden)$
  match:class = ^(brave-nn.*-Default)$

  float = true
  size = 500 700
  move =  1400 70
}

# NMTUI
windowrule {
  name = network-manager
  match:class = ^(nmtui)$

  float = true
  size = 1000 700
  center = true
}

# VLC
windowrule = opaque true, match:class ^(vlc)$

# Mission Center
windowrule = opaque true, match:class (io.missioncenter.MissionCenter)
