#    _               _
#   | |__   __ _ ___| |__  _ __ ___
#   | '_ \ / _` / __| '_ \| '__/ __|
#  _| |_) | (_| \__ \ | | | | | (__
# (_)_.__/ \__,_|___/_| |_|_|  \___|
#
# -----------------------------------------------------------------------------------------------------------------------------------------

source "$HOME/.config/shell/env"
source "$BASHDIR/config"
source "$SHELLDIR/aliases"
source "$SHELLDIR/autostart"

if [[ $(tty) == *"pts"* ]]; then
  eval "$(oh-my-posh init bash --config $HOME/.config/ohmyposh/blueish.omp.json)"
else
  eval "$(oh-my-posh init bash --config $HOME/.config/ohmyposh/zen.toml)"
fi
