#  _                                       _
# | | __ _ _   _  ___ _ __      _ __ _   _| | ___  ___
# | |/ _` | | | |/ _ \ '__|____| '__| | | | |/ _ \/ __|
# | | (_| | |_| |  __/ | |_____| |  | |_| | |  __/\__ \
# |_|\__,_|\__, |\___|_|       |_|   \__,_|_|\___||___/
#          |___/
#
# -----------------------------------------------------------------------------------------------------------------------------------------

layerrule {
    name = blurred layers
    match:namespace = waybar|rofi|gtk-layer-shell|gtk4-layer-shell|notifications|nwg-drawer

    blur = true
    blur_popups = true
    ignore_alpha = 0
}

layerrule {
    name = logout animation
    match:namespace = logout_dialog

    blur = true
    animation = fade
}
