---
- name: Arch Linux Setup
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ ansible_user_id }}"

  roles:
    - role: base
      tags: base
    - role: hyprland
      tags: hyprland
    - role: git
      tags: git
    - role: bitwarden
      tags: bitwarden
    # - theming
    # - development
    # - dotfiles
    # - scripts
    # - backup
